require("plugconf/nvim-tree")
require("plugconf/markdown").config()
require("plugconf/nvim-floaterm").config()
require("plugconf/nvim-comment").config()
require("plugconf/nvim-fzf").config()
require("plugconf/nvim-lualine")
require("plugconf/copilot").config()
-- require("plugconf/treesitter").config()
require("plugconf/nvim-dadbod").config()
require("plugconf/nvim-expand-region").config()
