local vo = vim.opt
local vg = vim.g
vo.autochdir = true -- Vim will change the current working directory whenever you open a file, switch buffers, delete a buffer or open/close a window.
vo.autoindent = true -- Copy indent from current line when starting a new line (typing <CR> in Insert mode or when using the "o" or "O" command)
vo.autoread = true -- When a file has been changed, automatically read it again
vo.clipboard = 'unnamedplus' -- A variant of the "unnamed" flag which uses the clipboard register "+" (quoteplus) instead of register "*" for all yank, delete, change and put operations which would normally go to the unnamed register
vo.cmdheight = 1 -- Number of screen lines to use for the command-line.  Helps avoiding hit-enter prompts.
vo.cursorline = true -- Highlight the text line of the cursor with CursorLine hl-CursorLine.
vo.encoding = 'utf-8' -- String-encoding used internally and for RPC communication.Always UTF-8.
vo.expandtab = true -- In Insert mode: Use the appropriate number of spaces to insert a <Tab>.
vo.fileencoding = 'utf-8' -- File content encoding for the buffer
vo.fillchars = {
	foldopen = "",
	foldclose = "",
	fold = " ",
	foldsep = " ",
	diff = "╱",
	eob = " ",
}
vo.ignorecase = true -- Ignore case in search patterns, cmdline-completion, when searching in the tags file, and expr-==.
vo.list = true -- List mode: By default, show tabs as ">", trailing spaces as "-", and non-breakable space characters as "+". Useful to see the difference between tabs and spaces and for trailing blanks. Further changed by the 'listchars' option
vo.listchars = 'tab:»·,nbsp:+,trail:·,extends:→,precedes:←'
vo.number = true -- Print the line number in front of each line
vo.ruler = true -- Show the line and column number of the cursor position, separated by a comma.  When there is room, the relative position of the displayed text in the file is shown on the far right:
vo.scroll = 0 -- Number of lines to scroll with CTRL-U and CTRL-D commands.
vo.shiftwidth = 2 -- Number of spaces to use for each step of (auto)indent.  Used for 'cindent', >>, <<, etc
vo.showcmd = true -- Show (partial) command in the last line of the screen.  Set this option off if your terminal is slow.
vo.smartcase = true -- Override the 'ignorecase' option if the search pattern contains upper case characters.
vo.smarttab = true -- When on, a <Tab> in front of a line inserts blanks according to 'shiftwidth'.  'tabstop' or 'softtabstop' is used in other places.  A <BS> will delete a 'shiftwidth' worth of space at the start of the line.
vo.softtabstop = 2 -- Number of spaces that a <Tab> counts for while performing editing operations, like inserting a <Tab> or using <BS>
vo.tabstop = 2 -- Number of spaces that a <Tab> in the file counts for.  Also see the :retab command, and the 'softtabstop' option
vo.termguicolors = true -- Enables 24-bit RGB color in the TUI.
vo.timeout = true -- This option and 'timeoutlen' determine the behavior when part of a mapped key sequence has been received.
vo.timeoutlen = 500 -- Time in milliseconds to wait for a mapped sequence to complete
vo.undofile = true -- When on, Vim automatically saves undo history to an undo file when writing a buffer to a file, and restores undo history from the same file on buffer read.
vo.updatetime = 100 -- If this many milliseconds nothing is typed the swap file will be written to disk (see crash-recovery)
vo.virtualedit = "block" -- Allow virtual editing in Visual block mode
vo.wildmenu = true -- When 'wildmenu' is on, command-line completion operates in an enhanced mode
vo.wrap = true -- This option changes how text is displayed.  It doesn't change the text in the buffer, see 'textwidth' for that.
